### ISSUE TITLE
脚本无法自动填充所在地点项

### ISSUE THREAD

**Issue by xiaoas** [k652/daily_fudan#1]
### 问题描述
脚本无法填入填报表单中
*所在地点(Current_ location)（请打开手机位置功能，并在手机权限设置中选择允许微信访问位置信息）* 项

### 当前行为
填报完成后，所在地点项显示为“点击获取地理位置”
![image](https://user-images.githubusercontent.com/14904657/89147576-99746780-d589-11ea-8df9-6b0855b8f9fd.png)

### 期待行为
填报完成后，所在地点项显示为“xxx XXX”

**Comment by potatoshred** [comment]
捂脸，用到现在一直没发现有这个问题，不过导员也没找过我😅，估计只是一个前端，不影响后台

**Comment by xiaoas** [comment]
😅而我就是被导员找了，说她看不见我的位置

**Comment by potatoshred** [comment]
已修改

**Comment by k652** [comment]
我晕，貌似又出问题了？
